### DISCUSSION TITLE
Trouble installing toffy_env on new computer based on openBlas error

### DISCUSSION THREAD

**Discussion by whitneyt1** [angelolab/toffy#312] [Q&A] [answered]
Hello,

When trying to install the toffy_env based on the environment.yml, I receive the following error: 

<img width="1404" alt="Screen Shot 2023-01-30 at 12 24 08 PM" src="https://user-images.githubusercontent.com/46573884/215588274-70d74c33-dde9-44b9-b974-a312152117d8.png">
<img width="1404" alt="Screen Shot 2023-01-30 at 12 24 23 PM" src="https://user-images.githubusercontent.com/46573884/215588282-3ac335a4-80b5-4a44-831a-d2c67870846b.png">

When trying to amend the environment.yml file to pip install pythran-openblas, I receive the error that it's incompatible with the python version. 

Thank you!

**Comment by srivarra** [comment, marked as answer]
Can you try running `conda install -c anaconda openblas` and see if that fixes it?

**Comment by whitneyt1** [comment]
I am still receiving the same error
<img width="492" alt="Screen Shot 2023-02-01 at 11 00 10 AM" src="https://user-images.githubusercontent.com/46573884/216138121-7bc097c5-a8cd-4d5f-a939-655da13f87f4.png">


<img width="746" alt="Screen Shot 2023-02-01 at 11 00 52 AM" src="https://user-images.githubusercontent.com/46573884/216138132-2c79b40c-566a-41f2-ad6d-4eee25d725b7.png">

**Comment by srivarra** [comment]
Could you share your `environment.yml` file @whitneyt1?

**Comment by whitneyt1** [comment]
Thanks Sri. once I redownloaded toffy/fresh environment.yml file, installation went smoothly. `conda install -c anaconda openblas` seemed to fix the problem!

**Comment by stantam** [comment]
Actually @srivarra, toffy_env installs, but when trying to import packages at the beginning of 3a, we receive this error:
<img width="746" alt="Screen Shot 2023-02-02 at 10 03 22 AM" src="https://user-images.githubusercontent.com/32483649/216406509-c5126047-c916-47dd-8333-3dd910d7f3ea.png">
<img width="746" alt="Screen Shot 2023-02-02 at 10 03 32 AM" src="https://user-images.githubusercontent.com/32483649/216406541-ea58b9cf-691d-4d6c-bbe6-017510f07554.png">
<img width="967" alt="Screen Shot 2023-02-02 at 10 03 41 AM" src="https://user-images.githubusercontent.com/32483649/216406547-9f8200b5-d464-4703-bd1a-4fa5098f1a5c.png">


Thanks!

**Reply by srivarra** [reply]
@whitneyt1 I was unable to replicate the this on my end, but I would like to you give this modified `environment.yml` file a try below and let me know if the imports in Notebook 3a is resolved or not.


<details>
<summary>environment.yml</summary>

```yaml

name: toffy_env
dependencies:
  - python=3.8
  - pip
  - openblas
  - numpy
  - scikit-learn
  - pip:
    - git+https://github.com/angelolab/mibi-bin-tools.git@v0.2.5
    - git+https://github.com/angelolab/tmi.git@v0.1.3
    # - jupyter>=1.0.0,<2
    - jupyter_contrib_nbextensions>=0.5.1,<1
    - jupyterlab>=3.4.3,<4
    - natsort>=0.8
    # - numpy>=1.22,<2
    - seaborn>=0.12.1,<1
    # - scikit-learn>=1.1.3,<2
    - traitlets>=5.2.2
    - watchdog>=2.1.6,<3
```
</details>
